name: Main

on:
  push:
    branches:
      - "*"

jobs:
  system-test:
    name: SystemTest
    uses: ./.github/workflows/system-test.yaml
    secrets: inherit
  release:
    needs: system-test
    name: Release
    uses: ./.github/workflows/release.yaml
    secrets: inherit
